### ISSUE TITLE
Input details

### ISSUE THREAD

**Issue by JIAYI-Scarlett** [ningnawang/Q-MAT#2]
Hi, thank you for your impressive work! 

I have a few questions regarding the input details. Is the .ma file representing the medial axis? It seems like the radius is not the radius of the medial axis spheres. Could you clarify how the input is generated and what the correct input format should be?

**Comment by bryceyin13** [comment]
Thanks for your question!
Actually, the .ma file DOES represent the medial axis. For example, a .ma file would be something like this:
 * numVertices numEdges numFaces
 * v x y z r
 * e v1 v2
 * f v1 v2 v3

Then, you can see vertices consisting of 4 dimensions with x y z representing coordinate of medial sphere center and r representing medial sphere radius.

**Comment by JIAYI-Scarlett** [comment]
![cut](https://github.com/user-attachments/assets/e89bb34a-1921-49b3-ac0c-7576943e7d4b)

**Comment by JIAYI-Scarlett** [comment]
Thank you for your response. I opened the .ma file you provided (bug.ma) in Blender using the method you described, but it seems that the file does not accurately represent the original shape. Additionally, the radius values appear to be much smaller than expected. Could you clarify if this is the intended input or if there might be an issue with the file?

**Comment by bryceyin13** [comment]
Well, I downloaded the file in the repo and found there really might be some problems with it. So thanks for your comment! I would later discuss with my collaborators to find a solution.
By the way, you can try this pair of files: 
[bug.zip](https://github.com/user-attachments/files/17123645/bug.zip)
It's also a bug model with more vertices than the one in the repo and it's correct on my device. You can have a try with it to see if it shows well on yours.

**Comment by JIAYI-Scarlett** [comment]
Thank you for your prompt response. The file works well on my device and appears reasonable.

And I was wondering if you could kindly explain how to obtain the initial medial axis (is it just by using SAT? If so, are there any specific parameters that need to be considered during this process?).

**Comment by ningnawang** [comment]
We haven't add the support for computing initial MAT using the way Q-MAT proposed (see the TODO in our ReadMe.md), but you can use other methods [MATFP](https://github.com/ningnawang/MATFP), [MATTopo](https://github.com/ningnawang/MATTopo), [VoxelCore](https://yajieyan.github.io/publication/voxelcore/overview/), [PowerCrust](https://github.com/kubkon/powercrust) for this purpose

**Comment by JIAYI-Scarlett** [comment]
Thank you! Looking forward to the update.

**Comment by Net-Maker** [comment]
I have implemented a version to generate ma file given OFF, see my implementation in https://github.com/Net-Maker/QMAT. I’ve made too many changes; I’ll submit a clean commit to this repo after this busy period.
